spring.application.name=healthcheck

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/healthcheck}
spring.datasource.username=${DB_USERNAME:healthuser}
spring.datasource.password=${DB_PASSWORD:healthpass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.connection-timeout=2000

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.connect-timeout=2s
spring.data.redis.timeout=2s